# -*- coding: utf-8 -*-
"""Projeto1AM.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KIWksJfX23uneVeRbAWEgVa1biZRXHvP
"""

from time import time
from datetime import datetime

import numpy as np
import pandas as pd

# algorithm parameters
K = 10  # number of partitions
m = 1.6  # fuzzification parameter
T = 10
e = 10e-10
p = 3  # number of views
n = 2000


def euclidean_distance(a, b):
    return np.linalg.norm(a - b)


def normalize_matrix(view):
    min_value = np.min(view)
    max_value = np.max(view)
    view = (view - min_value) / (max_value - min_value)
    return view


def dissimilarity_matrix(matrix, size):
    dis_matrix = np.zeros((size, size), dtype=float)
    for i in range(0, size):
        for j in range(0, size):
            dis_matrix[i, j] = euclidean_distance(a=matrix[i, :], b=matrix[j, :])
    return dis_matrix


def dist_object(i, k):
    acc = 0
    for j in range(0, p):
        acc += pesos[k][j] * dis_matrix[j][i][G[k][j]]
    return acc


def objective_function():
    objective = 0
    for k in range(0, K):
        for i in range(0, n):
            objective += np.power(U[i][k], m) * dist_object(i, k)
    return objective


def compute_u(i, k):
    membership = 0
    numerador = dist_object(i, k)
    for h in range(0, K):
        membership += np.power(numerador / dist_object(i, h), (1 / (m - 1)))
    membership = np.power(membership, -1)
    return membership


def compute_weigths():
    for j in range(0, p):
        for k in range(0, K):
            numerador = 1
            for h in range(0, p):
                soma = 0
                for i in range(0, n):
                    soma += np.power(U[i][k], m) * dis_matrix[h][i][G[k][h]]
                numerador = numerador * soma
            numerador = np.power(numerador, (1 / p))
            denominador = 0
            for i in range(0, n):
                denominador += np.power(U[i][k], m) * dis_matrix[j][i][G[k][j]]
            pesos[k][j] = numerador/denominador
    return pesos


print('Começou:', datetime.now())

# importing datasets
fac_dataset = pd.read_csv('../data_bases/mfeat_fac.csv', header=None)
fou_dataset = pd.read_csv('../data_bases/mfeat_fou.csv', header=None)
kar_dataset = pd.read_csv('../data_bases/mfeat_kar.csv', header=None)
print('Carregou os arquivos')
# convert data frames to array
fac_view = fac_dataset.iloc[:, :].values
fou_view = fou_dataset.iloc[:, :].values
kar_view = kar_dataset.iloc[:, :].values

# Normalize matrixes (feature scaling)
fac_norm = normalize_matrix(fac_view)
fou_norm = normalize_matrix(fou_view)
kar_norm = normalize_matrix(kar_view)
print('Normalize')
# compute dissimilarity matrixes
fac_dis = dissimilarity_matrix(matrix=fac_norm, size=n)
print('Computou fac_dis')
fou_dis = dissimilarity_matrix(matrix=fou_norm, size=n)
print('Computou fou_dis')
kar_dis = dissimilarity_matrix(matrix=kar_norm, size=n)
print('Computou kar_dis')

dis_matrix = [fac_dis, fou_dis, kar_dis]
pesos = np.ones((K, p), dtype=float)
U = np.zeros((n, K), dtype=float)
G = np.random.choice(n, size=(K, p), replace=False)

print('Start loop: ', datetime.now())
for i in range(0, n):
    for k in range(0, K):
        U[i][k] = compute_u(i, k)
J = objective_function()
print('Inicial J = ', J)
last_J = J + 10

t = 0
while (abs(J - last_J) >= e) and (t < T):
    last_J = J
    """Step 1"""
    G = np.random.choice(n, size=(K, p), replace=False)
    """Step 2"""
    pesos = compute_weigths()
    """Step 3"""
    for i in range(0, n):
        for k in range(0, K):
            U[i][k] = compute_u(i, k)
    J = objective_function()
    t += 1
    print('Iteração: ', t, 'Valor função objetivo: ', J)
print('Finalizou: ', datetime.now())
